{% set name = "dvc-data" %}
{% set version = "3.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ac227bb96ddbb68dd143c80d21360278511fcb3dce675ba744e92007166d63a6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools_scm >=6.3.1
  run:
    - fsspec >=2024.2.0
    - tqdm >=4.63.1,<5
    - python >=3.8
    - funcy >=1.14
    - dictdiffer >=0.8.1
    - pygtrie >=2.3.2
    - shortuuid >=0.5.0
    - dvc-objects >=4.0.1,<6
    - nanotime >=0.5.2
    - diskcache >=5.2.1
    - attrs >=21.3.0
    - sqltrie >=0.11.0,<1

test:
  imports:
    - dvc_data
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/iterative/dvc-data
  summary: DVC data management library
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - efiop
    - daavoo
    - pmrowla
    - shcheklein
    - skshetry
