{% set name = "dvc-data" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ad2374b2d9cd2c91ac7491ca7d6843978ad9d38972ff2eff86afa14978f2233d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools_scm >=6.3.1
  run:
    - python >=3.8
    - funcy >=1.14
    - dictdiffer >=0.8.1
    - pygtrie >=2.3.2
    - shortuuid >=0.5.0
    - dvc-objects <1,>=0.21.1
    - nanotime >=0.5.2
    - diskcache >=5.2.1
    - attrs >=21.3.0
    - sqltrie <1,>=0.3.1

test:
  imports:
    - dvc_data
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/iterative/dvc-data
  summary: DVC data management library
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - efiop
    - pmrowla
    - shcheklein
    - skshetry
